insert into standings2 values('Dorm','Rank','Points','Time');
insert into standings2 values('Apley Court','1','100','');
insert into standings2 values('Canaday Hall','3','100','');
insert into standings2 values('Grays Hall','2','100','');
insert into standings2 values('Greenough Hall','4','100','');
insert into standings2 values('Hollis Hall','5','100','');
insert into standings2 values('Holworthy Hall','6','100','');
insert into standings2 values('Hurlbut Hall','7','100','');
insert into standings2 values('Lionel Hall','8','100','');
insert into standings2 values('Massachusetts Hall','9','100','');
insert into standings2 values('Matthews Hall','10','100','');
insert into standings2 values('Mower Hall','11','100','');
insert into standings2 values('Pennypacker Hall','12','100','');
insert into standings2 values('Stoughton Hall','13','100','');
insert into standings2 values('Straus Hall','14','100','');
insert into standings2 values('Thayer Hall','15','100','');
insert into standings2 values('Weld Hall','16','100','');
insert into standings2 values('Wigglesworth Hall','17','100','');
insert into standings2 values('');
